<?php 
$req = Zend_Controller_Front::getInstance()->getRequest();
$controller = $req->getControllerName();
$title = 'Album';
?>
<div class="row">
    <div class="col-xs-12 col-md-12">
        <button 
            type="button" 
            class="btn btn-primary btn-lg js-btn-modal" 
            data-toggle="modal" 
            data-target="#myModal"
            data-modal-title="Adicionar <?php echo $title; ?>"
            data-modal-body="<?php echo $controller; ?>/add"
            data-form-success="<?php echo $controller; ?>"
        >
            <i class="icon-plus"></i> Adicionar <?php echo $title; ?>
        </button>
        <?php echo $this->paginator; ?>

        <div class="table-scrollable">
                <table class="table table-sm table-hover">
                    <thead class="thead-default">
                        <tr>
                            <th>
                                #
                            </th>
                            <th class="text-center">
                                Nome
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($this->paginator as $row) : ?>
                        <tr>
                            <td>
                                <?php echo $row->id; ?>
                            </td>
                            <td class="text-center">
                                    <?php echo $row->artist; ?>
                            </td>
                            <td class="text-center">
                                    <?php echo $row->title; ?>
                            </td>
                            <td class="text-center">
                                <button 
                                    type="button" 
                                    class="btn btn-default btn-lg js-btn-modal" 
                                    data-toggle="modal" 
                                    data-target="#myModal"
                                    data-modal-title="Editar <?php echo $title; ?>"
                                    data-modal-body="<?php echo $controller; ?>/edit/id/<?php
                                                      echo $this->escape($row->id); ?>"
                                    data-form-success="<?php echo $controller; ?>"
                                    data-form-edit="true"
                                >
                                    <span class="" >
                                    Editar
                                    </span>
                                </button>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
        <?php echo $this->paginator; ?>
    </div>
</div>