<!DOCTYPE html>
<html lang="pt-BR">
  <head>
    <?php
        $auth = Zend_Auth::getInstance()->getIdentity();
        $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8')
                         ->setName('viewport', 'width=device-width, initial-scale=1.0')
                         ->appendHttpEquiv('IE=edge,chrome=1', 'X-UA-Compatible');

        $this->headTitle($this->metaTitle)->setSeparator(' - ');
        $this->headTitle('ZF1');
        $this->headLink(
            array(
                'rel' => 'icon',
                'href' => '/favicon.ico'), 'PREPEND')
             ->prependStylesheet("/dist/css/style.min.css");

         $this->headScript()
                ->appendFile('https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js',
                  'text/javascript',
                  array('conditional' => 'lt IE 9'))
                ->appendFile('https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js',
                  'text/javascript',
                  array('conditional' => 'lt IE 9'))
                ->appendFile('/dist/js/app.js');

        echo $this->headTitle();
        echo $this->headMeta();
        echo $this->headLink();
        echo $this->headStyle();
    ?>
  </head>
  <body>
    <div class="container">
        <?php echo $this->partial('navbar.phtml'); ?>
        <!-- Main component for a primary marketing message or call to action -->
        <?php if(!is_null($auth)): ?>
          <div class="col-md-2">
            <?php echo $this->partial('menu.phtml'); ?>
          </div>
        <?php endif; ?>
        
        <div class="<?php echo (is_null($auth)) ? 'col-md-12' : 'col-md-10'; ?>">
            <div id="js-main-content">
                <!-- Default panel contents -->
                <?php echo $this->layout()->content; ?>
            </div>
        </div>
    </div> <!-- /container -->
    <?php 
      echo $this->partial('modal.phtml'); 
      echo $this->headScript();
    ?>
  </body>
</html>