<?php
$request    = Zend_Controller_Front::getInstance()->getRequest();
$module     = $request->getModuleName();
$controller = $request->getControllerName();
?>
<!-- Static navbar -->
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">ZF1 test</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="active">
          <a 
            class="js-main-menu"
            href="#"
            name="index"
            data-value="/home">Home</a>
        </li>
        <li>
          <a 
            class="js-main-menu"
            href="#"
            name="index"
            data-value="/admin">Admin</a>
        </li>
        <li><a href="#">Contact</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li class="dropdown-header">Nav header</li>
            <li><a href="#">Separated link</a></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <ul class="nav pull-right primary">
        <?php
          $auth = Zend_Auth::getInstance();
          if (!is_null($auth->getIdentity())) :
        ?>
        <li class="dropdown profile">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="glyphicon glyphicon-user"></i>
            <?php echo $auth->getIdentity()->getName(); ?>
            <b class="caret"></b>
            </a>
            <ul class="dropdown-menu secondary "> 
                <li class="">
                    <a href="/auth/logout">
                    <i class="glyphicon glyphicon-off"></i> Sair
                    </a>
                </li>
            </ul>
        </li>

	    <?php else : ?>
      <form 
          id="login" 
          action="/login" 
          method="post" 
          role="form" 
          class="navbar-form navbar-right login-form"
          enctype="application/x-www-form-urlencoded">
            <div class="input-prepend form-group">
                <input
                  type="text" 
                  class="form-control"
                  icon="ok"
                  placeholder="login"
                  prepend="&lt;i class=&quot;glyphicon glyphicon-user&quot; style=&quot;float: left;&quot;&gt;&lt;/i&gt;"
                  autocomplete="off" 
                  value=""
                  id="bG9naW5zZW5oYQ"
                  name="bG9naW5zZW5oYQ"
                  required
                />
            </div>
            <div class="input-prepend form-group">
                <input
                  type="password"
                  class="form-control"
                  icon="icon-key"
                  placeholder="senha"
                  prepend="&lt;i class=&quot;icon-key&quot; style=&quot;float: left;&quot;&gt;&lt;/i&gt;"
                  autocomplete="off"
                  value=""
                  id="cGFzc3dvcmRzZW5oYQ"
                  name="cGFzc3dvcmRzZW5oYQ"
                  required
                />
                
            </div>

            <button
              class="btn btn-green btn-large login-btn btn-success"
              buttons="danger info primary success warning inverse link"
              value="Sign In"
              type="submit"
              id="submit"
              name="submit"
            >Sign In</button>
        </form>
          <?php endif; ?>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container-fluid -->
</nav>
