<?php 
$auth = Zend_Auth::getInstance();
if (is_null($auth->getIdentity())) : ?>      
<div class="jumbotron">
        <div class="container">
            <!-- Example row of columns -->
            <div class="row">
                <div class="col-md-8">
                    <section id="main">
                        <h1>ZF</h1>
                    </section>
                </div>

                <div class="col-md-4">
                    <h2>Cadastre-se:</h2>
                    <section id="main">
                       <?php echo $this->registerForm; ?>
                    </section>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>
<?php echo $this->message; ?>